DROP TABLE IF EXISTS carritos_usuario;

CREATE TABLE carritos_usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firebaseUid VARCHAR(128) NOT NULL UNIQUE,
  items JSON NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
